/* Generated by exb-i18n-kit (wire). Shares the widget's intl with every module of this part,
   so strings outside the component tree follow the app language too. Safe to keep in git. */
import __messages from './translations/default'

let intl: any = null

/** Called by the entry component on every render. */
export function __setIntl (i: any): void { if (i && typeof i.formatMessage === 'function') intl = i }

/** App-language text for a key in translations/default.ts; English (with {values} filled) when there is none. */
export function __t (id: string, values?: { [key: string]: any }): string {
  const msg: string = (__messages as any)[id] ?? id
  if (intl) { try { return intl.formatMessage({ id, defaultMessage: msg }, values) } catch (e) { } }
  return String(msg).replace(/\{(\w+)\}/g, (m: string, k: string) => (values && values[k] != null ? String(values[k]) : m))
}

/** config.x || 'Default' made translatable: the app-language default when the value is empty or still the English default. */
export function __tc (value: any, id: string, values?: { [key: string]: any }): string {
  if (value == null || value === '' || value === (__messages as any)[id]) return __t(id, values)
  return value
}

/** Used in front of hand-written translators: the app-language text, or undefined to keep their own logic. */
export function __tryIntl (id: any, values?: any): string | undefined {
  if (!intl || typeof id !== 'string' || !intl.messages || typeof intl.messages[id] !== 'string') return undefined
  try { return intl.formatMessage({ id, defaultMessage: (__messages as any)[id] ?? id }, values) } catch (e) { return undefined }
}

/** The messages object, but every string comes from the app language when the widget intl has it. */
export const __m: any = new Proxy(__messages as any, {
  get: (target: any, key: any) => {
    const v = target[key]
    if (typeof key !== 'string' || typeof v !== 'string') return v
    const m = intl && intl.messages ? intl.messages[key] : undefined
    return typeof m === 'string' ? m : v
  }
})
